[program:agent7]
command=bash /idm/agents/agent7_inventory/bootstrap.sh
directory=/idm/agents/agent7_inventory
autostart=true
autorestart=true
stdout_logfile=/idm/system/logs/agent7.log
stderr_logfile=/idm/system/logs/agent.log
