[program:swarm_pod]
command=python3 -u /idm/run_swarm_pod.py
directory=/idm
autostart=true
autorestart=true
stdout_logfile=/idm/system/logs/swarm_pod.log
stderr_logfile=/idm/system/logs/swarm_pod_err.log
