[program:swarm_engine]
command=/idm/bootstrap.sh
directory=/idm
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stopsignal=TERM
stdout_logfile=/idm/system/logs/swarm_engine.out.log
stderr_logfile=/idm/system/logs/swarm_engine.err.log
